name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Build and test the project
      run: ./gradlew clean build

    - name: Run lint checks (optional)
      run: ./gradlew lint

    - name: Verify Kotlin compilation (optional)
      run: ./gradlew compileKotlin
